spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team_4_db
    username: root
    password: Irisviel95
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
