package Contracts;

public enum ContractsEntity {
    DETERMINATO,
    INDETERMINATO,
    PART_TIME,
    APPRENDISTATO,
    STAGE,
    INTERMITTENTE,
    PRESTAZIONI_OCCASIONALI,
    AUSILIARIO,
    CO_CO_CO,
    SOMMINISTRAZIONE
}
