spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scuola
    username: root
    password: 151002
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password:
    driver-class-name:  org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true